### ISSUE TITLE
Caching items?

### ISSUE THREAD

**Issue by timacdonald** [spatie/valuestore#13]
Ahoy!

1. Thanks for the fantastic package.

2. Would you consider a PR for the following:

Currently every time  you `->get('key')` a value it reaches out the the filesystem. Would you consider a PR to support storing the values in a cache within a class property.

Possible issue 1: There could be issues if the cache was a class instance property, if you had 2 instances changing the values in different places.

Solution to issue 1: So I was thinking a static class property with the filename as the identifying key (like Laravel Mix does for the mix manifest). That way if 2 instances of the Valuestore changed values in different places in the app - those changes would be present across both instances.

Possible issue 2: With all this considered there is also the possibility that some other class would modify the json file.

Possible solution 2: My thinking is people using this package probably don't have multiple things accessing the file - just different instances of the Valuestore....but I could be wrong!

If this is something you would consider I'm more than happy to help out with a PR - otherwise thanks again for the package!

Edit: I know this is probably a micro optimisation...

Edit 2: When setting values the cache and file values would sync.

**Comment by freekmurze** [comment]
I'd like to keep this package very simple, that's why I'm not in favour of adding caching mechanisms to it. 

You can easily create your own class, let it extend `Valuestore` and add a `getCached` method to it with any logic you'd like.

**Comment by timacdonald** [comment]
No worries - thanks!

**Comment by timacdonald** [comment]
Incase anyone else is interested - I just put this functionality in a little wrapper package: https://github.com/timacdonald/cached-valuestore

Thanks again for the great package Spatie!
