### ISSUE TITLE
[Request] add caching

### ISSUE THREAD

**Issue by fletch3555** [spatie/valuestore#18]
Can you add caching to this? Even if it's just a local variable in that class, so it's only cached per request.

Right now, a call to get() will call all() twice, and each call to all() reads the entire file into memory.  This seems extremely inefficient.

I could PR it for you, but it'll take a day or two as I'm busy this weekend

**Comment by freekmurze** [comment]
Caching is out of scope for this package. I'd like to keep the code as simple as it can be. If it is giving you performance problem, maybe using a database is a better solution for your use case.

I did make a small performance improvement in the `get()` function.

**Comment by freekmurze** [comment]
Sure, send a PR and we'll take it from there.

**Comment by timacdonald** [comment]
@fletch3555 if you are still after some local caching on this, I made a cached version a while ago: https://github.com/timacdonald/cached-valuestore
