### ISSUE TITLE
Getting value while using dot notiation

### ISSUE THREAD

**Issue by stpronk** [spatie/valuestore#25]
I was busy while working with your package and I noticed that it might be handy if it could support dot notation for getting and storing the vallues. I'm pretty new to pull requests so I will do it this way:

    public function get(string $name, $default = null){

        $all = Arr::dot($this->all());

        if (! array_key_exists($name, $all)) {
            return $default;
        }

        return $all[$name]    

    }

This way you can also nest values if you want.

**Comment by freekmurze** [comment]
Feel free to send a PR with tests that adds this to the package.
