### ISSUE TITLE
Perfomance question.

### ISSUE THREAD

**Issue by Briareos17** [spatie/valuestore#26]
I am using Redis for my laravel project and want to ask - is there any perfomance reason to cache stored in json files data to redis what is faster?

**Comment by atymic** [comment]
Redis will be much faster than this library, as it's storing values in memory rather than on the disk. The speed of this package is dependant on the IO performance of the disk.

For cache, i'd use Redis if possible, or if you want to use disk caching, use the inbuilt laravel `file` cache.
