### ISSUE TITLE
Be able to count by value, too

### ISSUE THREAD

**Issue by e-edgren** [spatie/valuestore#28]
As it is right now, the function `count()` for `$valuestore = Valuestore::make($pathToFile);` can only count how many values there are in a file. But how about to also count based on a specific value? Here's my thought:

Someone has added values to a file using `$valuestore->put()` and the website adds the files to a folder where the folder name is the visitor's id. Lets say this is about comments for a blog. Each visitor has their own folder with data files in them. On the website, you want to count all comments from a specific date. As it is right now with valuestore, this is not possible.

Can you please make this happen?

**Comment by freekmurze** [comment]
I'd like to keep this package simple, so I'm not going to implement this right now.
